#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	cd "${MODULE_SRCDIR}"
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--with-tcltk="${PMODULES_HOME}" \
		|| exit 1
}

function em.build() {
        cd "${MODULE_SRCDIR}"
        make
}

em.add_to_family 'Tools'
em.set_runtime_dependencies 'Tcl' 'Tk'
em.set_docfiles 'COPYING' 'README'
em.make_all

# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
