#!/bin/bash

source $(dirname $0)/../../../lib/libem.bash

function em.pre_configure() {
	./autogen.sh
}

function em.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-h5hut \
		--enable-hdf5 \
		--enable-root \
		--with-pic
}

em.add_to_family 'Compiler'
em.set_runtime_dependencies "${COMPILER}" 'hdf5_serial' 'root'
em.set_build_dependencies 'autoconf' 'automake' 'libtool' "${COMPILER}" 'hdf5_serial' 'H5hut_serial' 'root'
em.make_all

