#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	:
}

function em.build() {
	case ${OS} in
		Linux )
			declare -x LDFLAGS="-lintl"
			;;
		Darwin )
			declare -x LDFLAGS="-lintl -liconv -framework CoreFoundation"
			;;
	esac

	cd "${MODULE_SRCDIR}"
	make -e
}

function em.install() {
	cd "${MODULE_SRCDIR}"
	declare -x DESTDIR="${PREFIX}"
	declare -x prefix=''
	make -e install
}

function em.cleanup_build() {
	cd "${MODULE_SRCDIR}"
	make -e realclean
}

em.add_to_family 'Tools'
em.make_all

# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
