#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	CC=$MPICC
	CXX=$MPICXX
	F77=$MPIF77
	F90=$MPIF90
	FC=$MPIFC
	FORTRAN=$MPIFORTRAN

	rm -f CMakeCache.txt
	cmake \
		-DCMAKE_BUILD_TYPE=RELEASE \
		-DCMAKE_INSTALL_PREFIX="${PREFIX}" \
		"${MODULE_SRCDIR}" \
		|| exit 1 
}

em.add_to_family 'MPI'
em.set_runtime_dependencies "${COMPILER}" "${MPI}"
em.set_build_dependencies 'cmake' "${COMPILER}" "${MPI}"
em.set_docfiles LICENSE README
em.make_all

