OPAL/2.2.1_slurm	stable	gcc/8.4.0 openmpi/3.1.6_slurm boost/1.73.0_slurm hdf5/1.10.6_slurm H5hut/2.0.0rc6_slurm gsl/2.6 parmetis/4.0.3_slurm trilinos/12.18.1_slurm amrex/18.07_3d_slurm b:cmake/3.15.5
OPAL/2.2.1-1_slurm	stable	gcc/8.4.0 openmpi/3.1.6_slurm boost/1.73.0_slurm hdf5/1.10.6_slurm H5hut/2.0.0rc6_slurm gsl/2.6 parmetis/4.0.3_slurm trilinos/12.18.1_slurm amrex/18.07_3d_slurm b:cmake/3.15.5
OPAL/2.4.0_slurm	stable	gcc/8.4.0 openmpi/3.1.6_slurm boost/1.73.0_slurm hdf5/1.10.6_slurm H5hut/2.0.0rc6_slurm gsl/2.6 parmetis/4.0.3_slurm trilinos/12.18.1_slurm amrex/18.07_3d_slurm b:cmake/3.15.5

OPAL/2021.1.0_slurm	stable	gcc/10.3.0 openmpi/4.0.5-1_slurm boost/1.76.0_slurm hdf5/1.10.7_slurm H5hut/2.0.0rc6_slurm gsl/2.7 trilinos/13.0.1_slurm amrex/18.07_3d_slurm MITHRA/2.0_slurm b:cmake/3.20.5 b:binutils/2.29

OPAL/2022.1.0_slurm	stable	gcc/10.4.0 openmpi/4.1.4_slurm boost/1.79.0_slurm hdf5/1.10.8_slurm H5hut/2.0.0rc6_slurm gsl/2.7 trilinos/13.0.1_slurm amrex/18.07_3d_slurm MITHRA/2.0_slurm b:cmake/3.20.5 b:binutils/2.29
