#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.pre_configure() {
	./autogen.sh
}

function em.configure() {
	CC=$MPICC
	CXX=$MPICXX
	F77=$MPIF77
	F90=$MPIF90
	FC=$MPIFC
	FORTRAN=$MPIFORTRAN
	#( cd "${MODULE_SRCDIR}" && ./autogen.sh )
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-parallel \
		--enable-debug \
		--enable-vtkconverter \
		--with-hdf5=$HDF5_PREFIX \
		--with-pic \
		|| exit 1
}

function em.build() {
	make -C src
	make -C tools 
}

function em.install() {
	make -C src install
	make -C tools install
}


em.add_to_family 'HDF5'
em.set_runtime_dependencies "${COMPILER}" "${MPI}" 'hdf5'
em.set_build_dependencies   "autoconf" "automake" "libtool" "${COMPILER}" "${MPI}" "vtk" "hdf5"
em.set_docfiles 'AUTHORS' 'COPYING'
em.make_all

