#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	CC=$MPICC CXX=$MPICXX cmake \
		-DCMAKE_INSTALL_PREFIX="${PREFIX}" \
		-DCMAKE_BUILD_TYPE=RELEASE \
		"${MODULE_SRCDIR}"
}

em.add_to_family 'MPI'
em.set_runtime_dependencies "${COMPILER}" "${MPI}"
em.set_build_dependencies 'cmake' "${COMPILER}" "${MPI}"
em.set_docfiles 'license.txt' 'README.txt'
em.make_all


