#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--with-gmp=$GMP_PREFIX \
		--disable-shared \
		|| exit 1
}

# use system gcc to compile
declare -rx CC=gcc

module use 'Libraries'

em.add_to_family 'Libraries'
em.set_build_dependencies 'gmp'
em.make_all
