#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--disable-shared \
		|| exit 1
}

# use system gcc to compile
declare -rx CC=gcc
declare -rx CPP=/usr/bin/cpp

em.add_to_family 'Libraries'
em.make_all

