#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		|| exit 1
}

function em.post_install() {
	ln -fs "${PREFIX}/bin/python${V%%.*}" "${PREFIX}/bin/python"
	ln -fs "${PREFIX}/include/python${V%.*}m" "${PREFIX}/include/python"
	ln -fs "${PREFIX}/include/python${V%.*}m" "${PREFIX}/include/python${V%.*}"
}

em.add_to_family 'Programming'
em.set_runtime_dependencies ""
em.set_build_dependencies   "${COMPILER}"
em.make_all

